framework:
    secret: %secret%
    templating:
        engines: [twig]
    profiler:
        enabled: %kernel.debug%

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database.host%"
        dbname:   "%database.name%"
        user:     "%database.user%"
        password: "%database.password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        result_cache_driver:
            type: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: %monolog_action_level%
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
